version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=askme_db
      - POSTGRES_USER=askme_user
      - POSTGRES_PASSWORD=askme_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U askme_user -d askme_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
      
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  centrifugo:
    image: centrifugo/centrifugo:v5
    restart: always
    volumes:
      - centrifugo_data:/centrifugo/data
      - ./conf/centrifugo.json:/centrifugo/config.json 

    environment:
      - CENTRIFUGO_HTTP_PORT=8035
      - CENTRIFUGO_HTTP_ADDRESS=0.0.0.0

    ports:
      - "8035:8035"  
    command: centrifugo -c config.json

    depends_on:
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8035/health"]
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  postgres_data:
  centrifugo_data: